/**
 * CodebaseScanner — static analysis of a project directory.
 *
 * scan()         → walks the directory tree and detects stack
 * generateDraft() → produces a codebase.md draft from scan results
 *
 * No LLM calls. Static filesystem analysis only.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import type { CodebaseScanResult, DirectoryNode } from '../types.js'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Directories excluded from tree walk. */
const EXCLUDED_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', '.next', '.turbo',
  'coverage', '.cache', '.output', 'out', 'tmp', '.tmp',
])

/** Maximum depth for directory tree walk. */
const MAX_DEPTH = 3

// ---------------------------------------------------------------------------
// scan
// ---------------------------------------------------------------------------

/**
 * Scan a project root directory and return a `CodebaseScanResult`.
 * All filesystem operations are synchronous for simplicity.
 */
export function scan(projectRoot: string): CodebaseScanResult {
  const tree = walkDirectory(projectRoot, 0)
  const packageJson = readJsonFile(path.join(projectRoot, 'package.json'))
  const tsconfig = readJsonFile(path.join(projectRoot, 'tsconfig.json'))

  const deps = extractDeps(packageJson)
  const devDeps = extractDevDeps(packageJson)

  return {
    root: projectRoot,
    tree,
    packageJson: packageJson ?? undefined,
    frameworks: detectFrameworks(deps, devDeps, projectRoot),
    testFrameworks: detectTestFrameworks(devDeps),
    styling: detectStyling(deps, devDeps, projectRoot),
    hasTypeScript: hasTypeScriptSupport(deps, devDeps, projectRoot),
    strictMode: detectStrictMode(tsconfig),
  }
}

// ---------------------------------------------------------------------------
// generateDraft
// ---------------------------------------------------------------------------

/**
 * Generate a codebase.md draft from scan results.
 * Clearly marked as DRAFT — requires developer review before use.
 */
export function generateDraft(result: CodebaseScanResult): string {
  const tree = renderTree(result.tree, 0)
  const stack = buildStackSummary(result)
  const stackLine = stack.length > 0 ? `\n<!-- Stack: ${stack} -->\n` : ''

  return `# Codebase Map
${stackLine}

<!-- DRAFT — Generated by \`mexai map\`. Review and edit before using. -->

## Structure

\`\`\`
${tree.trim()}
\`\`\`

## Key Files

<!-- Add key files and their purposes here. Examples:
- \`src/index.ts\` — main entry point
- \`src/types.ts\` — shared type definitions
-->

## Conventions

${buildConventionStubs(result)}

## Patterns

<!-- Document common implementation patterns used in this codebase.
Examples:
- Error handling: always use typed errors with error codes
- Data fetching: use SWR with typed hooks
-->

## Do Not Touch

<!-- List files or directories that must not be modified.
Examples:
- \`dist/\` — generated build output
- \`*.generated.ts\` — auto-generated files
-->
`
}

// ---------------------------------------------------------------------------
// Tree walker
// ---------------------------------------------------------------------------

function walkDirectory(dir: string, depth: number): DirectoryNode {
  const name = path.basename(dir)

  if (depth >= MAX_DEPTH) {
    return { name, type: 'directory' }
  }

  let entries: fs.Dirent[]
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true })
  } catch {
    return { name, type: 'directory' }
  }

  // Sort: directories first, then files, both alphabetically
  const sorted = entries.sort((a, b) => {
    if (a.isDirectory() && !b.isDirectory()) return -1
    if (!a.isDirectory() && b.isDirectory()) return 1
    return a.name.localeCompare(b.name)
  })

  const children: DirectoryNode[] = []
  for (const entry of sorted) {
    if (entry.name.startsWith('.') && entry.name !== '.github') continue

    if (entry.isDirectory()) {
      if (EXCLUDED_DIRS.has(entry.name)) continue
      children.push(walkDirectory(path.join(dir, entry.name), depth + 1))
    } else if (entry.isFile()) {
      children.push({ name: entry.name, type: 'file' })
    }
  }

  return { name, type: 'directory', children }
}

function renderTree(node: DirectoryNode, depth: number): string {
  const indent = '  '.repeat(depth)
  const suffix = node.type === 'directory' ? '/' : ''
  const lines = [`${indent}${node.name}${suffix}`]

  if (node.children) {
    for (const child of node.children) {
      lines.push(renderTree(child, depth + 1))
    }
  }
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Detection helpers
// ---------------------------------------------------------------------------

function readJsonFile(filePath: string): Record<string, unknown> | null {
  try {
    const raw = fs.readFileSync(filePath, 'utf8')
    return JSON.parse(raw) as Record<string, unknown>
  } catch {
    return null
  }
}

function extractDeps(pkg: Record<string, unknown> | null): Record<string, string> {
  if (!pkg) return {}
  const deps = pkg.dependencies
  if (typeof deps !== 'object' || deps === null) return {}
  return deps as Record<string, string>
}

function extractDevDeps(pkg: Record<string, unknown> | null): Record<string, string> {
  if (!pkg) return {}
  const devDeps = pkg.devDependencies
  if (typeof devDeps !== 'object' || devDeps === null) return {}
  return devDeps as Record<string, string>
}

function detectFrameworks(
  deps: Record<string, string>,
  devDeps: Record<string, string>,
  root: string
): string[] {
  const frameworks: string[] = []

  // Next.js
  if ('next' in deps || fileExists(root, 'next.config.js') || fileExists(root, 'next.config.ts') || fileExists(root, 'next.config.mjs')) {
    frameworks.push('Next.js')
  }
  // Vite
  if ('vite' in devDeps || fileExists(root, 'vite.config.ts') || fileExists(root, 'vite.config.js')) {
    frameworks.push('Vite')
  }
  // Express
  if ('express' in deps) {
    frameworks.push('Express')
  }
  // Remix
  if (Object.keys(deps).some((k) => k.startsWith('@remix-run/'))) {
    frameworks.push('Remix')
  }
  // Astro
  if ('astro' in deps) {
    frameworks.push('Astro')
  }
  // React (standalone, not via Next/Remix)
  if ('react' in deps && !frameworks.includes('Next.js') && !frameworks.includes('Remix')) {
    frameworks.push('React')
  }

  return frameworks
}

function detectTestFrameworks(devDeps: Record<string, string>): string[] {
  const result: string[] = []
  if ('vitest' in devDeps) result.push('Vitest')
  if ('jest' in devDeps || '@types/jest' in devDeps) result.push('Jest')
  return result
}

function detectStyling(
  deps: Record<string, string>,
  devDeps: Record<string, string>,
  root: string
): string[] {
  const result: string[] = []
  if ('tailwindcss' in devDeps || fileExists(root, 'tailwind.config.js') || fileExists(root, 'tailwind.config.ts')) {
    result.push('Tailwind CSS')
  }
  if ('styled-components' in deps) result.push('styled-components')
  if (globExists(root, '.module.css')) result.push('CSS Modules')
  return result
}

function hasTypeScriptSupport(
  deps: Record<string, string>,
  devDeps: Record<string, string>,
  root: string
): boolean {
  return 'typescript' in devDeps || 'typescript' in deps || fileExists(root, 'tsconfig.json')
}

function detectStrictMode(tsconfig: Record<string, unknown> | null): boolean {
  if (!tsconfig) return false
  const compilerOptions = tsconfig.compilerOptions
  if (typeof compilerOptions !== 'object' || compilerOptions === null) return false
  const opts = compilerOptions as Record<string, unknown>
  return opts.strict === true
}

function fileExists(root: string, filename: string): boolean {
  return fs.existsSync(path.join(root, filename))
}

/** Crude glob-like check: does any file in root (non-recursive) match a suffix? */
function globExists(root: string, suffix: string): boolean {
  try {
    const entries = fs.readdirSync(root, { withFileTypes: true })
    return entries.some((e) => e.isFile() && e.name.endsWith(suffix))
  } catch {
    return false
  }
}

// ---------------------------------------------------------------------------
// Draft builders
// ---------------------------------------------------------------------------

function buildStackSummary(result: CodebaseScanResult): string {
  const parts: string[] = []
  if (result.frameworks.length > 0) parts.push(`Frameworks: ${result.frameworks.join(', ')}`)
  if (result.testFrameworks.length > 0) parts.push(`Testing: ${result.testFrameworks.join(', ')}`)
  if (result.styling.length > 0) parts.push(`Styling: ${result.styling.join(', ')}`)
  if (result.hasTypeScript) parts.push('TypeScript: yes')
  return parts.join(' | ')
}

function buildConventionStubs(result: CodebaseScanResult): string {
  const stubs: string[] = []

  if (result.hasTypeScript) {
    stubs.push(result.strictMode
      ? '- TypeScript strict mode enabled — no implicit any'
      : '- TypeScript (strict mode not enabled)')
  }
  if (result.frameworks.includes('Next.js')) {
    stubs.push('- App Router / Pages Router: <!-- specify which -->')
    stubs.push('- Server Components: <!-- document usage pattern -->')
  }
  if (result.testFrameworks.includes('Vitest')) {
    stubs.push('- Tests: co-located with source (`*.test.ts`), Vitest runner')
  } else if (result.testFrameworks.includes('Jest')) {
    stubs.push('- Tests: Jest runner')
  }
  if (result.styling.includes('Tailwind CSS')) {
    stubs.push('- Styling: Tailwind CSS utility classes')
  }

  if (stubs.length === 0) {
    stubs.push('<!-- Document your conventions here -->')
  }

  return stubs.join('\n')
}
