/**
 * ExportEngine — generates flat files (AGENTS.md, CLAUDE.md, .cursorrules)
 * from the project store for AI agents that don't support MCP.
 *
 * All exports:
 * - Respect the token budget
 * - Include a generated-by header with timestamp
 * - Include a "do not edit directly" warning
 */

import type { Layer } from '../types.js'
import { StoreError } from '../types.js'
import { readLayer } from '../store/store-manager.js'
import { getTokenBudget } from '../store/config-manager.js'
import { parseContext, formatContextForInjection } from '../formats/context-format.js'
import { parseCodebase, formatCodebaseForInjection } from '../formats/codebase-format.js'
import { parseRules, formatRulesForInjection } from '../formats/rules-format.js'

// ---------------------------------------------------------------------------
// Decisions formatter (always full list, never truncated in exports)
// ---------------------------------------------------------------------------

function formatDecisionsSection(decisions: { date: string; title: string; rationale: string }[]): string {
  if (decisions.length === 0) return '## Decisions\n\n_(none)_'
  const items = decisions
    .map((d) => `### ${d.date}: ${d.title}\n\n${d.rationale}`)
    .join('\n\n')
  return `## Decisions\n\n${items}`
}

// ---------------------------------------------------------------------------
// Export functions
// ---------------------------------------------------------------------------

/** MCP tool guidance block — injected into every AGENTS.md and CLAUDE.md export. */
const MCP_TOOL_GUIDANCE = `## mexai MCP — How to use

If the mexai MCP server is connected (run \`mexai serve\` or configure via \`mexai connect\`):

- **At session start:** call the \`context_read\` tool to load the latest project context.
- **After significant work:** call \`context_save\` to stage decisions and state updates for review.
- **Do NOT** use \`@mexai-context\` or any \`mexai://\` URI — resource URIs are not supported. Use tools only.

Available tools: \`context_read\`, \`context_save\`, \`context_list\`, \`codebase_read\`, \`rules_read\``

/**
 * Generate AGENTS.md content for the given project slug.
 * Full three-layer export for agents that read AGENTS.md.
 */
export function exportAgentsMd(slug: string): string {
  const budget = getTokenBudget()
  const header = buildHeader('AGENTS.md', slug)

  const parts: string[] = [header, MCP_TOOL_GUIDANCE]

  const rulesRaw = safeReadLayer(slug, 'rules')
  if (rulesRaw !== null) {
    const rules = parseRules(rulesRaw)
    const { content } = formatRulesForInjection(rules, budget.rules)
    parts.push(content)
  }

  const contextRaw = safeReadLayer(slug, 'context')
  if (contextRaw !== null) {
    const ctx = parseContext(contextRaw)
    parts.push(formatContextForInjection(ctx, budget.context))
    // Always include all decisions explicitly — injection may have truncated them
    if (ctx.decisions.length > 0) {
      parts.push(formatDecisionsSection(ctx.decisions))
    }
  }

  const codebaseRaw = safeReadLayer(slug, 'codebase')
  if (codebaseRaw !== null) {
    const cb = parseCodebase(codebaseRaw)
    parts.push(formatCodebaseForInjection(cb, budget.codebase))
  }

  return parts.join('\n\n---\n\n') + '\n'
}

/**
 * Generate CLAUDE.md content for the given project slug.
 * Same as AGENTS.md but with Claude-specific guidance and no MCP instructions
 * (since this export is for Claude.ai browser, not Claude Code).
 */
export function exportClaudeMd(slug: string): string {
  const budget = getTokenBudget()
  const header = buildHeader('CLAUDE.md', slug)
  const claudeNote = `> **Context injected by mexai.** This file is auto-generated — edit your context via \`mexai edit\` instead.`

  const parts: string[] = [header, claudeNote, MCP_TOOL_GUIDANCE]

  const contextRaw = safeReadLayer(slug, 'context')
  if (contextRaw !== null) {
    const ctx = parseContext(contextRaw)
    parts.push(formatContextForInjection(ctx, budget.context))
    // Always include all decisions explicitly — injection may have truncated them
    if (ctx.decisions.length > 0) {
      parts.push(formatDecisionsSection(ctx.decisions))
    }
  }

  const rulesRaw = safeReadLayer(slug, 'rules')
  if (rulesRaw !== null) {
    const rules = parseRules(rulesRaw)
    const { content } = formatRulesForInjection(rules, budget.rules)
    parts.push(content)
  }

  const codebaseRaw = safeReadLayer(slug, 'codebase')
  if (codebaseRaw !== null) {
    const cb = parseCodebase(codebaseRaw)
    parts.push(formatCodebaseForInjection(cb, budget.codebase))
  }

  return parts.join('\n\n---\n\n') + '\n'
}

/**
 * Generate .cursorrules content for the given project slug.
 * Rules-focused export with full context parity: includes Current State
 * and all Decisions so agents have complete project awareness.
 */
export function exportCursorRules(slug: string): string {
  const budget = getTokenBudget()
  const header = `# Cursor Rules — generated by mexai (${timestamp()})\n# Do not edit directly — run \`mexai export\` to regenerate.\n`

  const parts: string[] = [header]

  const rulesRaw = safeReadLayer(slug, 'rules')
  if (rulesRaw !== null) {
    const rules = parseRules(rulesRaw)
    const { content } = formatRulesForInjection(rules, budget.rules)
    parts.push(content)
  }

  // Context: identity + current state + all decisions (same sections as AGENTS.md / CLAUDE.md)
  const contextRaw = safeReadLayer(slug, 'context')
  if (contextRaw !== null) {
    const ctx = parseContext(contextRaw)
    const contextSection = [
      `## Project: ${ctx.frontmatter.name}`,
      ``,
      ctx.identity.trim(),
      ``,
      `**Current state:** ${ctx.currentState.trim()}`,
    ].join('\n')
    parts.push(contextSection)
    // Always include all decisions — never truncated in exports
    if (ctx.decisions.length > 0) {
      parts.push(formatDecisionsSection(ctx.decisions))
    }
  }

  return parts.join('\n\n') + '\n'
}

// ---------------------------------------------------------------------------
// Export completeness audit
// ---------------------------------------------------------------------------

export interface ExportCompleteness {
  target: string
  hasRules: boolean
  hasIdentity: boolean
  hasCurrentState: boolean
  hasDecisions: boolean
  complete: boolean
}

/**
 * Audit the completeness of all export targets for a project.
 * Used by `mexai export` to print a summary and warn on gaps.
 */
export function auditExportCompleteness(slug: string): ExportCompleteness[] {
  const contextRaw = safeReadLayer(slug, 'context')
  const rulesRaw = safeReadLayer(slug, 'rules')

  const hasRules = rulesRaw !== null && rulesRaw.trim().length > 10
  let hasIdentity = false
  let hasCurrentState = false
  let hasDecisions = false

  if (contextRaw !== null) {
    const ctx = parseContext(contextRaw)
    hasIdentity = ctx.identity.trim().length > 0
    hasCurrentState = ctx.currentState.trim().length > 0
    hasDecisions = ctx.decisions.length > 0
  }

  const makeEntry = (target: string): ExportCompleteness => ({
    target,
    hasRules,
    hasIdentity,
    hasCurrentState,
    hasDecisions,
    complete: hasIdentity && hasCurrentState,
  })

  return [
    makeEntry('AGENTS.md'),
    makeEntry('CLAUDE.md'),
    makeEntry('.cursorrules'),
  ]
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function buildHeader(filename: string, slug: string): string {
  return [
    `<!-- ${filename} — generated by mexai on ${timestamp()} -->`,
    `<!-- Project: ${slug} — do not edit directly. Run \`mexai export\` to regenerate. -->`,
  ].join('\n')
}

function timestamp(): string {
  return new Date().toISOString().slice(0, 19).replace('T', ' ') + ' UTC'
}

function safeReadLayer(slug: string, layer: Layer): string | null {
  try {
    return readLayer(slug, layer)
  } catch (err) {
    if (err instanceof StoreError && err.code === 'LAYER_NOT_INITIALIZED') {
      return null
    }
    throw err
  }
}
