import { describe, it, expect, vi, beforeEach } from 'vitest'
import { exportAgentsMd, exportClaudeMd, exportCursorRules } from './export-engine.js'

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

vi.mock('../store/store-manager.js', () => ({
  readLayer: vi.fn(),
}))

vi.mock('../store/config-manager.js', () => ({
  getTokenBudget: vi.fn(() => ({
    context: 250,
    codebase: 300,
    rules: 150,
    total: 700,
  })),
}))

import { readLayer } from '../store/store-manager.js'

const MOCK_CONTEXT = `---
name: My Project
slug: my-project
domain: web
stack:
  - TypeScript
status: active
createdAt: "2026-04-09T10:00:00.000Z"
updatedAt: "2026-04-09T10:00:00.000Z"
---

## Identity

Building a local-first AI context manager.

## Current State

Phase 2 complete.

## Decisions

## Open Threads

`

const MOCK_RULES = `# Agent Rules

## Code Quality

- Write tests for all new code
- No implicit any

## Review Gates

- Tests must pass before commit
`

const MOCK_CODEBASE = `# Codebase Map

## Key Files

- \`src/index.ts\` — entry point

## Conventions

- Named exports everywhere
`

function setupMocks(): void {
  vi.mocked(readLayer).mockImplementation((_slug: string, layer: string) => {
    if (layer === 'context') return MOCK_CONTEXT
    if (layer === 'rules') return MOCK_RULES
    if (layer === 'codebase') return MOCK_CODEBASE
    return ''
  })
}

// ---------------------------------------------------------------------------
// exportAgentsMd
// ---------------------------------------------------------------------------

describe('exportAgentsMd', () => {
  beforeEach(setupMocks)

  it('includes generated-by header', async () => {
    const output = await exportAgentsMd('my-project')
    expect(output).toContain('generated by mexai')
    expect(output).toContain('AGENTS.md')
  })

  it('includes do-not-edit warning', async () => {
    const output = await exportAgentsMd('my-project')
    expect(output).toContain('do not edit directly')
  })

  it('includes all three layers', async () => {
    const output = await exportAgentsMd('my-project')
    expect(output).toContain('Agent Rules')
    expect(output).toContain('My Project')
    expect(output).toContain('Key Files')
  })

  it('orders layers: rules → context → codebase', async () => {
    const output = await exportAgentsMd('my-project')
    const rulesIdx = output.indexOf('Agent Rules')
    const contextIdx = output.indexOf('My Project')
    const codebaseIdx = output.indexOf('Key Files')
    expect(rulesIdx).toBeLessThan(contextIdx)
    expect(contextIdx).toBeLessThan(codebaseIdx)
  })

  it('respects token ceiling (output is reasonable size)', async () => {
    const output = await exportAgentsMd('my-project')
    // 700 tokens ≈ 2800 chars. With headers and separators, allow some overhead
    expect(output.length).toBeLessThan(10_000)
  })
})

// ---------------------------------------------------------------------------
// exportClaudeMd
// ---------------------------------------------------------------------------

describe('exportClaudeMd', () => {
  beforeEach(setupMocks)

  it('includes generated-by header with CLAUDE.md label', async () => {
    const output = await exportClaudeMd('my-project')
    expect(output).toContain('CLAUDE.md')
  })

  it('includes Claude-specific guidance note', async () => {
    const output = await exportClaudeMd('my-project')
    expect(output).toContain('mexai')
  })

  it('includes all three layers', async () => {
    const output = await exportClaudeMd('my-project')
    expect(output).toContain('My Project')
    expect(output).toContain('Agent Rules')
    expect(output).toContain('Key Files')
  })

  it('is valid markdown (contains headings)', async () => {
    const output = await exportClaudeMd('my-project')
    expect(output).toMatch(/^#+\s/m)
  })
})

// ---------------------------------------------------------------------------
// exportCursorRules
// ---------------------------------------------------------------------------

describe('exportCursorRules', () => {
  beforeEach(setupMocks)

  it('includes generated-by comment', async () => {
    const output = await exportCursorRules('my-project')
    expect(output).toContain('generated by mexai')
  })

  it('includes rules content', async () => {
    const output = await exportCursorRules('my-project')
    expect(output).toContain('Code Quality')
    expect(output).toContain('Write tests')
  })

  it('includes brief project context (identity)', async () => {
    const output = await exportCursorRules('my-project')
    expect(output).toContain('My Project')
    expect(output).toContain('local-first')
  })

  it('stays within rules token ceiling', async () => {
    const output = await exportCursorRules('my-project')
    // 150 token ceiling + brief context + headers. Should be well under 5000 chars
    expect(output.length).toBeLessThan(5_000)
  })
})
