/**
 * ExportEngine — generates flat files (AGENTS.md, CLAUDE.md, .cursorrules)
 * from the project store for AI agents that don't support MCP.
 *
 * All exports:
 * - Respect the token budget
 * - Include a generated-by header with timestamp
 * - Include a "do not edit directly" warning
 */

import type { Layer } from '../types.js'
import { StoreError } from '../types.js'
import { readLayer } from '../store/store-manager.js'
import { getTokenBudget } from '../store/config-manager.js'
import { parseContext, formatContextForInjection } from '../formats/context-format.js'
import { parseCodebase, formatCodebaseForInjection } from '../formats/codebase-format.js'
import { parseRules, formatRulesForInjection } from '../formats/rules-format.js'

// ---------------------------------------------------------------------------
// Decisions formatter (always full list, never truncated in exports)
// ---------------------------------------------------------------------------

function formatDecisionsSection(decisions: { date: string; title: string; rationale: string }[]): string {
  if (decisions.length === 0) return '## Decisions\n\n_(none)_'
  const items = decisions
    .map((d) => `### ${d.date}: ${d.title}\n\n${d.rationale}`)
    .join('\n\n')
  return `## Decisions\n\n${items}`
}

// ---------------------------------------------------------------------------
// Export functions
// ---------------------------------------------------------------------------

/**
 * Generate AGENTS.md content for the given project slug.
 * Full three-layer export for agents that read AGENTS.md.
 */
export function exportAgentsMd(slug: string): string {
  const budget = getTokenBudget()
  const header = buildHeader('AGENTS.md', slug)

  const parts: string[] = [header]

  const rulesRaw = safeReadLayer(slug, 'rules')
  if (rulesRaw !== null) {
    const rules = parseRules(rulesRaw)
    const { content } = formatRulesForInjection(rules, budget.rules)
    parts.push(content)
  }

  const contextRaw = safeReadLayer(slug, 'context')
  if (contextRaw !== null) {
    const ctx = parseContext(contextRaw)
    parts.push(formatContextForInjection(ctx, budget.context))
    // Always include all decisions explicitly — injection may have truncated them
    if (ctx.decisions.length > 0) {
      parts.push(formatDecisionsSection(ctx.decisions))
    }
  }

  const codebaseRaw = safeReadLayer(slug, 'codebase')
  if (codebaseRaw !== null) {
    const cb = parseCodebase(codebaseRaw)
    parts.push(formatCodebaseForInjection(cb, budget.codebase))
  }

  return parts.join('\n\n---\n\n') + '\n'
}

/**
 * Generate CLAUDE.md content for the given project slug.
 * Same as AGENTS.md but with Claude-specific guidance and no MCP instructions
 * (since this export is for Claude.ai browser, not Claude Code).
 */
export function exportClaudeMd(slug: string): string {
  const budget = getTokenBudget()
  const header = buildHeader('CLAUDE.md', slug)
  const claudeNote = `> **Context injected by mexai.** This file is auto-generated — edit your context via \`mexai edit\` instead.`

  const parts: string[] = [header, claudeNote]

  const contextRaw = safeReadLayer(slug, 'context')
  if (contextRaw !== null) {
    const ctx = parseContext(contextRaw)
    parts.push(formatContextForInjection(ctx, budget.context))
    // Always include all decisions explicitly — injection may have truncated them
    if (ctx.decisions.length > 0) {
      parts.push(formatDecisionsSection(ctx.decisions))
    }
  }

  const rulesRaw = safeReadLayer(slug, 'rules')
  if (rulesRaw !== null) {
    const rules = parseRules(rulesRaw)
    const { content } = formatRulesForInjection(rules, budget.rules)
    parts.push(content)
  }

  const codebaseRaw = safeReadLayer(slug, 'codebase')
  if (codebaseRaw !== null) {
    const cb = parseCodebase(codebaseRaw)
    parts.push(formatCodebaseForInjection(cb, budget.codebase))
  }

  return parts.join('\n\n---\n\n') + '\n'
}

/**
 * Generate .cursorrules content for the given project slug.
 * Rules-focused export; under the rules token ceiling.
 */
export function exportCursorRules(slug: string): string {
  const budget = getTokenBudget()
  const header = `# Cursor Rules — generated by mexai (${timestamp()})\n# Do not edit directly — run \`mexai export\` to regenerate.\n`

  const parts: string[] = [header]

  const rulesRaw = safeReadLayer(slug, 'rules')
  if (rulesRaw !== null) {
    const rules = parseRules(rulesRaw)
    const { content } = formatRulesForInjection(rules, budget.rules)
    parts.push(content)
  }

  // Append a brief context summary (identity + current state only)
  const contextRaw = safeReadLayer(slug, 'context')
  if (contextRaw !== null) {
    const ctx = parseContext(contextRaw)
    const brief = `## Project: ${ctx.frontmatter.name}\n\n${ctx.identity.trim()}\n\n**Current state:** ${ctx.currentState.trim()}`
    parts.push(brief)
  }

  return parts.join('\n\n') + '\n'
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function buildHeader(filename: string, slug: string): string {
  return [
    `<!-- ${filename} — generated by mexai on ${timestamp()} -->`,
    `<!-- Project: ${slug} — do not edit directly. Run \`mexai export\` to regenerate. -->`,
  ].join('\n')
}

function timestamp(): string {
  return new Date().toISOString().slice(0, 19).replace('T', ' ') + ' UTC'
}

function safeReadLayer(slug: string, layer: Layer): string | null {
  try {
    return readLayer(slug, layer)
  } catch (err) {
    if (err instanceof StoreError && err.code === 'LAYER_NOT_INITIALIZED') {
      return null
    }
    throw err
  }
}
